---
- name: install libvirt dependency
  community.general.pacman:
    name:
      # - cdrtools # required by libvirt terraform
      #- vim # but conflict with gvim => xxd => steam
      #- gvim # for guestfish
      - libguestfs # for guestfish
      - dnsmasq # libvirt deps
      - openbsd-netcat # for virt-manager gui
      - libxml2 # xmllint in network hook
      - cloud-image-utils # cloud-localds
    state: present
    reason: explicit
    reason_for: all
  become: true

- name: install libvirt with pacman
  community.general.pacman:
    name:
      - qemu-full # libvirt backend
      - libvirt
      - virt-manager
    state: present
    reason: explicit
    reason_for: all
  become: true
