---
- ansible.builtin.include_role:
    name: novicecpp.homeconfig.install_apt_packages
  vars:
    apt_packages:
      - libvirt-daemon
      - libvirt-clients
      # python binding for ansible
      - python3-libvirt
      - python3-lxml
      # cloud-localds command
      - cloud-image-utils
    install_apt_packages_upgrade: false
