---
# will be used in ssh_config template
- set_fact:
    # require
    var_mode: "{{ autossh_tunnel_mode }}"  # require
    # defaults/main.yml
    var_user: "{{ autossh_tunnel_user }}"
    var_hostname: "{{ autossh_tunnel_hostname }}"
    var_remote_port: "{{ autossh_tunnel_remote_port }}"
    var_listen_ip: "{{ autossh_tunnel_listen_ip }}"

- name: install autossh
  include_tasks: "{{ ansible_distribution }}.yml"

- name: add autossh user {{ autossh_tunnel_user }}
  ansible.builtin.user:
    name: "{{ autossh_tunnel_user }}"
    create_home: true
    home: "/home/{{ autossh_tunnel_user }}"
    shell: /usr/sbin/nologin
    password_lock: true
  become: true

- name: ensure .ssh dir
  ansible.builtin.file:
    path: /home/{{ autossh_tunnel_user }}/.ssh
    state: directory
    owner: "{{ autossh_tunnel_user }}"
    group: "{{ autossh_tunnel_user }}"
    mode: '0700'
  become: true

- name: copy ssh config
  ansible.builtin.template:
    src: dot-ssh/ssh_config_autossh.j2
    dest: "/home/{{ autossh_tunnel_user }}/.ssh/ssh_config_autossh_{{ autossh_tunnel_mode }}"
    owner: "{{ autossh_tunnel_user }}"
    group: "{{ autossh_tunnel_user }}"
    mode: '0600'
  become: true

# key is usually in autossh/<servername>/
- name: copy private key
  ansible.builtin.copy:
    content: >
      {{ lookup('community.general.passwordstore', autossh_tunnel_passkey_path, returnall=true) }}
    dest: "/home/{{ autossh_tunnel_user }}/.ssh/ssh_privkey"
    owner: "{{ autossh_tunnel_user }}"
    group: "{{ autossh_tunnel_user }}"
    mode: '0600'
  become: true

- name: copy known_hosts
  ansible.builtin.copy:
    content: >
      {{ lookup('community.general.passwordstore', autossh_tunnel_known_hosts_passkey_path, returnall=true) }}
    dest: /home/{{ autossh_tunnel_user }}/.ssh/known_hosts
    owner: "{{ autossh_tunnel_user }}"
    group: "{{ autossh_tunnel_user }}"
    mode: '0600'
  become: true

- name: copy unit
  ansible.builtin.template:
    src: etc/systemd/system/autossh.service.j2
    dest: /etc/systemd/system/autossh-{{ autossh_tunnel_mode }}.service
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart unit

- name: enable unit
  ansible.builtin.systemd_service:
    name: autossh-{{ autossh_tunnel_mode }}
    daemon_reload: true
    state: started
    enabled: true
  become: true
