---
- name: add autossh user
  ansible.builtin.user:
    name: "{{ autossh_tunnel_user }}"
    create_home: true
    home: "/home/{{ autossh_tunnel_user }}"
    shell: /bin/sh  # server side need to have actual shell. Otherwise, we cannot login.
    password_lock: true
  become: true

- name: ensure .ssh dir
  ansible.builtin.file:
    path: "/home/{{ autossh_tunnel_user }}/.ssh"
    state: directory
    owner: "{{ autossh_tunnel_user }}"
    group: "{{ autossh_tunnel_user }}"
    mode: '0700'
  become: true

# key is usually in autossh/<servername>/
- name: copy authorized_keys
  ansible.builtin.copy:
    content: >
      {{ lookup('community.general.passwordstore', autossh_tunnel_authorized_keys_path, returnall=true) }}
    dest: "/home/{{ autossh_tunnel_user }}/.ssh/authorized_keys"
    owner: "{{ autossh_tunnel_user }}"
    group: "{{ autossh_tunnel_user }}"
    mode: '0600'
  become: true
