---
- name: ensure /opt/ping-wg directory
  ansible.builtin.file:
    path: /opt/ping-wg
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: install ping-wg systemd unit
  ansible.builtin.template:
    src: etc/systemd/system/ping-wg.service.j2
    dest: /etc/systemd/system/ping-wg.service
    mode: '0644'
  become: true

- name: install ping-wg.sh
  ansible.builtin.copy:
    src: opt/ping-wg/ping-wg.sh
    dest: /opt/ping-wg/ping-wg.sh
    mode: '0755'
  become: true
  notify: restart ping-wg

- name: ensure wg-quick unit override directory
  ansible.builtin.file:
    path: /etc/systemd/system/wg-quick@{{ wg_interface }}.service.d
    state: directory
    owner: root
    group: root
    mode: '0755'
  become: true

- name: copy wg-quick unit override
  ansible.builtin.copy:
    src: etc/systemd/system/wg-quick@.service.d/override.conf
    dest: /etc/systemd/system/wg-quick@{{ wg_interface }}.service.d/override.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart wireguard

- name: reload daemon and start
  ansible.builtin.systemd:
    name: ping-wg.service
    state: started
    daemon_reload: true
    enabled: true
  become: true
