---
- name: install wireguard-tools
  include_tasks: "dist/{{ ansible_distribution }}.yml"
# variable
# wg_interfaces:
#   - name: wg-interface
#     enabled: true/false
- name: apply wireguard config
  include_tasks: client.yml
  vars:
    task_vars: "{{ item }}"
  loop: "{{ wg_interfaces }}"

- name: ensure scripts dir
  ansible.builtin.file:
    path: /etc/wireguard/scripts/
    state: directory
    mode: '0700'
    owner: root
    group: root
  become: true

- name: copy pre-postup.sh script
  ansible.builtin.copy:
    src: etc/wireguard/scripts/pre-postup.sh
    dest: /etc/wireguard/scripts/pre-postup.sh
    mode: '0700'
    owner: root
    group: root
  become: true
