---
- name: install wireguard-tools
  include_tasks: "dist/{{ ansible_distribution }}.yml"
# variable
# wg_interfaces:
#   - name: wg-interface
#     enabled: true/false
- name: apply wireguard config
  include_tasks: client.yml
  vars:
    wg_interface: "{{ item.name }}"
    should_enable: "{{ item.enabled | default(true) }}"
    ping_enable: "{{ item.ping_enabled | default(false) }}"
    gateway_ip: "{{ item.ping_server | default('127.0.0.1') }}"

  loop: "{{ wg_interfaces }}"
