---
# variable
# wg_interfaces:
#   - name: wg-interface
#     enabled: true/false
- name: apply wireguard config
  include_tasks: client.yml
  vars:
    wg_interface: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  loop: "{{ wg_interfaces }}"
