---
- name: copy pacman config
  ansible.builtin.copy:
    src: etc/pacman.conf
    dest: /etc/pacman.conf
    mode: '0644'
    owner: root
    group: root
  become: true

- name: update pacman cache (pacman -Sy)
  community.general.pacman:
    update_cache: true
  become: true

# keyring need to be upgrade for newly signed packages.
- name: pacman update archlinux-keyring
  community.general.pacman:
    name:
      - archlinux-keyring
    state: latest
    reason: explicit
    reason_for: all
  become: true

- name: remove conflict packages
  include_tasks: conflict.yml
  loop: "{{ pacman_conflict_packages }}"
  loop_control:
    loop_var: p

- name: pacman install packages
  community.general.pacman:
    name: "{{ pacman_pacstrap_packages + pacman_packages + pacman_extra_packages }}"
    reason: explicit
    reason_for: all
    state: present
  become: true

# need to upgrade later due to deps conflict (or packages move from core to extra)
- name: pacman upgrade
  community.general.pacman:
    upgrade: true
    upgrade_extra_args: --ask 4
  become: true

- name: install aur and packages
  ansible.builtin.include_tasks: aur.yml
  when: pacman_install_aur
