---
- name: ensure coredns directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: root
    group: root
  loop:
    - /etc/sysusers.d
    - /etc/tmpfiles.d
    - "/etc/{{ coredns_appname }}"
    - "/opt/{{ coredns_appname }}/bin"
  become: true

- name: downloads coredns
  include_role:
    name: novicecpp.homeconfig.download_and_extract
  vars:
    download_url: "{{ coredns_download_url }}"
    checksum: "{{ coredns_download_checksum }}"
    path:
      - src: coredns
        dest: /opt/{{ coredns_appname }}/bin
    copy_become: true

- name: copy deployment config
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: root
    group: root
  loop:
    - src: "etc/systemd/system/coredns.service.j2"
      dest: /etc/systemd/system/{{ coredns_appname }}.service
    - src: "etc/sysusers.d/coredns-sysusers.conf.j2"
      dest: /etc/sysusers.d/{{ coredns_appname }}-sysusers.conf
    - src: "etc/tmpfiles.d/coredns-tmpfiles.conf.j2"
      dest: /etc/tmpfiles.d/{{ coredns_appname }}-tmpfiles.conf
    - src: "etc/logrotate.d/coredns-log.conf.j2"
      dest: /etc/logrotate.d/{{ coredns_appname }}-log.conf
  become: true

- name: enable systemd unit
  ansible.builtin.systemd_service:
    name: "{{ coredns_appname }}"
    enabled: true
    daemon_reload: true
  become: true

- name: trigger systemd-sysusers and systemd-tmpfiles
  shell: systemd-tmpfiles --create; systemd-sysusers;
  become: true
