---
- name: calculate coredns binary
  ansible.builtin.shell:
    cmd: |
      sha256sum /opt/{{ coredns_appname }}/bin/coredns | awk '{printf $1}'
  args:
    executable: /bin/bash
  changed_when: false
  register: cmd_sha256sum_coredns_bin

- name: install coredns
  include_tasks: install.yml
  when: cmd_sha256sum_coredns_bin.stdout != coredns_bin_checksum

- name: unit daemon reload
  ansible.builtin.systemd_service:
    daemon_reload: true
  become: true

- name: copy coredns config
  ansible.builtin.copy:
    src: "{{ coredns_config_path }}"
    dest: "/etc/{{ coredns_appname }}/"
    owner: root
    group: root
    mode: '0644'
  notify: restart coredns
  tags:
    - config
    - always
  become: true
