---
- name: Check if version file exist
  stat:
    path: ~/.local/share/noisetouch/version
  register: result

- name: install noisetouch
  include_tasks: install.yml
  when: (not result.stat.exists) or (lookup('ansible.builtin.file', '~/.local/share/noisetouch/version') != noisetorch_git_head)
