---
- name: install rust
  include_tasks: "{{ ansible_distribution }}.yml"

- name: Install cargo app
  community.general.cargo:
    name: "{{ cargo_packages + cargo_extra_packages }}"
    locked: true
