---
k8s_client_downloads:
  helm:
    v3.13.1:
      url: https://get.helm.sh/helm-v3.13.1-linux-amd64.tar.gz
      checksum: sha256:98c363564d00afd0cc3088e8f830f2a0eeb5f28755b3d8c48df89866374a1ed0
    v3.15.2:
      url: https://get.helm.sh/helm-v3.15.2-linux-amd64.tar.gz
      checksum: sha256:2694b91c3e501cff57caf650e639604a274645f61af2ea4d601677b746b44fe2
    v3.17.0:
      url: https://get.helm.sh/helm-v3.17.0-linux-amd64.tar.gz
      checksum: sha256:fb5d12662fde6eeff36ac4ccacbf3abed96b0ee2de07afdde4edb14e613aee24
    v3.17.1:
      url: https://get.helm.sh/helm-v3.17.1-linux-amd64.tar.gz
      checksum: sha256:3b66f3cd28409f29832b1b35b43d9922959a32d795003149707fea84cbcd4469

  kubectl:
    v1.28.3:
      url: https://dl.k8s.io/v1.28.3/kubernetes-client-linux-amd64.tar.gz
      checksum: sha256:b7b44a3e8c2587e2d517ddc4d024f4263582758ff52fffab2e08276986914cb6
    v1.29.5:
      url: https://dl.k8s.io/v1.29.5/kubernetes-client-linux-amd64.tar.gz
      checksum: sha256:b8a5a916c23660206eb7b6f35e48796e424b42cf86a65a792e8442490e466215
    v1.31.6:
      url: https://dl.k8s.io/v1.31.6/kubernetes-client-linux-amd64.tar.gz
      checksum: sha512:dd3d8723e7ff54aa4c8a1087d961c8f604b8dce5a6981357daea9b8e1882efbfaf9e226afc35cdc277e2ac06f6ef3bd9867c21158d9ae917d02ade7c245f8610
    v1.32.1:
      url: https://dl.k8s.io/v1.32.1/kubernetes-client-linux-amd64.tar.gz
      checksum: sha512:3eff144cdc8db4681fcf9b2205fa732ea7836e7878d9cc5617171970bbf80813eea45d08e1d00f6d652b6364c4a099e3e40a2a6a3ddad11a9896c73cda3118d2

  kubelogin:
    v1.28.0:
      url: https://github.com/int128/kubelogin/releases/download/v1.28.0/kubelogin_linux_amd64.zip
      checksum: sha256:83282148fcc70ee32b46edb600c7e4232cbad02a56de6dc17e43e843fa55e89e
    v1.34.0:
      url: https://github.com/int128/kubelogin/releases/download/v1.34.0/kubelogin_linux_amd64.zip
      checksum: sha256:9f68bd3fb1427fd12befe492a45a309bcb341d1bdff0d090052cfe3833291529
  kubectx:
    v0.9.5:
      url: https://github.com/ahmetb/kubectx/archive/refs/tags/v0.9.5.tar.gz
      checksum: sha256:c94392fba8dfc5c8075161246749ef71c18f45da82759084664eb96027970004
  kustomize:
    v5.2.1:
      url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.2.1/kustomize_v5.2.1_linux_amd64.tar.gz
      checksum: sha256:88346543206b889f9287c0b92c70708040ecd5aad54dd33019c4d6579cd24de8
    v5.4.2:
      url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz
      checksum: sha256:881c6e9007c7ea2b9ecc214d13f4cdd1f837635dcf4db49ce4479898f7d911a3
    v5.6.0:
      url: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.6.0/kustomize_v5.6.0_linux_amd64.tar.gz
      checksum: sha256:54e4031ddc4e7fc59e408da29e7c646e8e57b8088c51b84b3df0864f47b5148f

k8s_client_components:
  - kubectl
  - kubectx
  - helm
  - kustomize

helm_download_url: "{{ k8s_client_downloads['helm'][helm_version]['url'] }}"
helm_download_checksum: "{{ k8s_client_downloads['helm'][helm_version]['checksum'] }}"

kubectl_download_url: "{{ k8s_client_downloads['kubectl'][kubectl_version]['url'] }}"
kubectl_download_checksum: "{{ k8s_client_downloads['kubectl'][kubectl_version]['checksum'] }}"

kubelogin_download_url: "{{ k8s_client_downloads['kubelogin'][kubelogin_version]['url'] }}"
kubelogin_download_checksum: "{{ k8s_client_downloads['kubelogin'][kubelogin_version]['checksum'] }}"

kubectx_download_url: "{{ k8s_client_downloads['kubectx'][kubectx_version]['url'] }}"
kubectx_download_checksum: "{{ k8s_client_downloads['kubectx'][kubectx_version]['checksum'] }}"

kustomize_download_url: "{{ k8s_client_downloads['kustomize'][kustomize_version]['url'] }}"
kustomize_download_checksum: "{{ k8s_client_downloads['kustomize'][kustomize_version]['checksum'] }}"


## default version

helm_version: v3.17.1
kubectl_version: v1.32.1
kubectx_version: v0.9.5
kubelogin_version: v1.34.0
kustomize_version: v5.6.0
