---
- name: restart iptables
  ansible.builtin.systemd_service:
    name: iptables
    state: restarted
  become: true

- name: restart systemd-resovled
  ansible.builtin.systemd_service:
    name: systemd-resovled
    state: restarted
  become: true
