---
- name: install libvirt with pacman
  community.general.pacman:
    name:
      - qemu-full # libvirt backend
      - dnsmasq
      - libvirt
      - virt-manager
      - gnu-netcat # for virt-manager gui
    state: present
  become: true
