---
- name: install libvirt
  include_tasks: '{{ ansible_distribution }}.yml'

- name: Add user to group
  ansible.builtin.user:
    name: "{{ ansible_user_id }}"
    shell: /bin/bash
    groups: libvirt
    append: true
  become: true

- set_fact:
    should_start: "{{ start | default(false) }}"

- name: enable libvirt unit
  ansible.builtin.systemd:
    state: started
    name: "{{ item }}"
    enabled: true
  loop:
    - libvirtd.service
    - libvirtd.socket
    - libvirtd-ro.socket
    - libvirtd-admin.socket
  become: true
  when: should_start
