---
namespace: "novicecpp"
name: "homeconfig"
version: "0.1.0"
readme: "README.md"
authors:
  - Thanayut Seethongchuen (thanayut.see@outlook.com)
dependencies:
  - "kewlfft.aur": ">=0.11.1"
  - "community.general": ">=8.1.0"

#license:
#repository: "https://www.github.com/my_org/my_collection"
