---
- name: get checksum
  ansible.builtin.stat:
    path: "{{ ansible_env.HOME }}/.local/bin/kustomize"
    get_attributes: false
    get_mime: false
    get_checksum: true
    checksum_algo: sha256
  register: current_checksum

- name: downloads kustomize
  include_role:
    name: download_and_extract
  vars:
    download_url: "{{ kustomize_download_url }}"
    checksum: "{{ kustomize_download_checksum }}"
    path:
      - src: kustomize
        dest: ~/.local/bin/
  when: not current_checksum.stat.exists or current_checksum.stat.checksum != (kustomize_binary_checksum | split(':') | last)

- name: export kustomize bash completion
  ansible.builtin.shell:
    cmd: "./kustomize completion bash > ~/.bash_completion.d/kustomize.bash"
    executable: /bin/bash
    chdir: "{{ ansible_env.HOME }}/.local/bin"
