---
- name: copy iptables rules
  ansible.builtin.copy:
    src: etc/iptables/iptables.rules
    dest: /etc/iptables/iptables.rules
    mode: '0644'
    owner: root
    group: root
  notify: restart iptables
  become: true

# this step will fail when first install nftables
# restart it once and rerun again
- name: enable iptables unit
  ansible.builtin.systemd_service:
    name: iptables
    state: started
    enabled: true
  become: true
