---
- name: enable systemd-resolve now
  ansible.builtin.systemd_service:
    name: systemd-resolved
    state: started
    enabled: true
  become: true

- name: copy resolv.conf
  ansible.builtin.copy:
    src: "etc/resolv-ipv6-support.conf"
    dest: /etc/resolv-ipv6-support.conf
    mode: '0644'
    owner: root
    group: root
  become: true

- name: replace /etc/resolv.conf to custom systemd-resolved stub
  ansible.builtin.file:
    src: /etc/resolv-ipv6-support.conf
    dest: /etc/resolv.conf
    force: true
    state: link
  notify: restart systemd-resolved
  become: true

- name: get stat of resoved.conf in inventory_dir
  ansible.builtin.stat:
    path: "{{ inventory_dir }}/files/etc/systemd/resolved.conf"
  register: st

- name: copy systemd-resolved config
  ansible.builtin.copy:
    src: "{{ inventory_dir }}/files/etc/systemd/resolved.conf"
    dest: /etc/systemd/resolved.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart systemd-resolved
  when: st.stat.exists
  become: true

- name: copy systemd-resolved default config
  ansible.builtin.copy:
    src: "etc/systemd/resolved.conf"
    dest: /etc/systemd/resolved.conf
    mode: '0644'
    owner: root
    group: root
  notify: restart systemd-resolved
  when: not st.stat.exists
  become: true
