---
- name: makes sure systemd-networkd is stop
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - systemd-networkd
  become: true

- name: enable services
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - NetworkManager
    - bluetooth
  become: true

- name: enable gui
  block:
    - name: enable display manager
      ansible.builtin.systemd:
        name: "{{ os_config_display_manager }}"
        enabled: true
      become: true
    - name: systemctl get-default
      ansible.builtin.shell: systemctl get-default
      register: result
      changed_when: false
      become: true
    - name: set-default graphical.target
      ansible.builtin.shell: systemctl set-default graphical.target
      when: result.stdout != "graphical.target"
      become: true
