---
- name: copy original firefox desktop
  ansible.builtin.copy:
    src: /usr/share/applications/firefox.desktop
    dest: ~/.local/share/applications/firefox.desktop
    mode: '0644'

- name: modify StartupWMClass
  ansible.builtin.lineinfile:
    path: ~/.local/share/applications/firefox.desktop
    regexp: '^StartupWMClass='
    line: StartupWMClass=firefoxbase

- name: create ff-profile
  include_tasks: ff-profile.yml
  loop: "{{ firefox_desktop_profiles }}"
  loop_control:
    loop_var: _profile_name

- name: run update-desktop-database
  ansible.builtin.shell:
    cmd: update-desktop-database ~/.local/share/applications/
